name: Provision EC2 and Deploy Website

on: 
  push:
    branches:
      - main

jobs:
  setupInfra:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{steps.tf.outputs.ec2_ip}}
      ec2_key: ${{steps.tf.outputs.ec2_key}}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init 
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1

      - name: Get Terraform outputs
        id: tf
        run: |
          echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
          echo "ec2_key<<EOF" >> $GITHUB_OUTPUT
          terraform output -raw ec2_private_key >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


  deploy:
    needs: setupInfra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.setupInfra.outputs.ec2_ip }}
          username: ubuntu
          key: ${{ needs.setupInfra.outputs.ec2_key }}
          script: |
            # Wait until Docker is ready
            until sudo docker info >/dev/null 2>&1; do
                echo "Waiting for Docker daemon..."
                sleep 10
            done


            git init
            git remote add origin https://github.com/Yogesh-sa1n1/UserRegisterationDevOps.git
            git fetch
            git reset --hard origin/main

            # Run Docker Compose (build and start containers)
            sudo docker-compose up -d --build
     